services:
        web:
        build: .
        container_name: rashboard
        network_mode: host
        environment:
              - DATABASE_URL= postgresql://username:password@127.0.0.1:5432/databasename
              - RAILS_MASTER_KEY
