services:
  web:
    build: .
    network_mode: host
    environment:
      - DATABASE_URL: postgresql://username:password@127.0.0.1:5432/databasename
      - RAILS_MASTER_KEY
    ports:
      - "3000:80"
